services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    environment:
      - DJANGO_SETTINGS_MODULE=airbnb_project.settings
      - PYTHONPATH=/usr/src/app
      - OPEN_WEATHER_KEY=8f884bbc55dd13d138fcba344300aa52  # Certifique-se de definir sua chave real
    env_file:
      - ./app/.env  # Se você estiver usando um arquivo .env para outras variáveis
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app_dev
volumes:
  postgres_data: