# Generated by Django 5.1.2 on 2024-10-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_stay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stay',
            options={'verbose_name': 'Estadia', 'verbose_name_plural': 'Estadias'},
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='weather_description',
            new_name='weather',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='weather_icon',
        ),
        migrations.RemoveField(
            model_name='stay',
            name='weather_main',
        ),
        migrations.AddField(
            model_name='stay',
            name='feels_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
