# Generated by Django 5.1.2 on 2024-10-18 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0005_alter_stay_availability_365_alter_stay_feels_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], default='csv', max_length=10, verbose_name='Tipo de arquivo'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de envio'),
        ),
    ]
